controllers:
  resource:
    path: ../src/Presentation/Controller/
    namespace: App\Presentation\Controller
  type: attribute
api_doc:
  path: /api/doc
  controller: nelmio_api_doc.controller.swagger_ui

api_doc_json:
  path: /api/doc.json
  controller: nelmio_api_doc.controller.swagger